name: Semantic Release

on:
  workflow_dispatch:  
   
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python3 -m pip install python-semantic-release
           
    - name: Python Semantic Release
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        semantic-release publish -D commit_author="github-actions <action@github.com>"
      env:
        GH_TOKEN: ${{ secrets.TEST_MERGE }}
             

#     - name: Python Semantic Release
#       uses: relekang/python-semantic-release@master
#       with:
#         github_token: ${{ secrets.TEST_MERGE }}
